apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: shahin-grc
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: "shahin_admin"
  POSTGRES_PASSWORD: "Shahin@GRC2026!"
  POSTGRES_DB: "shahin_grc"
  POSTGRES_AUTH_DB: "shahin_grc"
  REPLICATION_USER: "replicator"
  REPLICATION_PASSWORD: "Replicator@GRC2026!"
  CONNECTION_STRING: "Host=pgbouncer;Port=6432;Database=shahin_grc;Username=shahin_admin;Password=Shahin@GRC2026!;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=100"
  AUTH_CONNECTION_STRING: "Host=pgbouncer;Port=6432;Database=shahin_grc;Username=shahin_admin;Password=Shahin@GRC2026!;Pooling=true;Minimum Pool Size=2;Maximum Pool Size=20"
